services:
  database-tests:
    image: postgres:latest
    container_name: superchat-test
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - '5433:5432'

  database:
    env_file:
      - path: './.env'
        required: true
    image: postgres:latest
    container_name: superchat-postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    env_file:
      - path: './.env'
        required: true
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  backend:
    build: ./superchat-api
    container_name: superchat-app
    restart: always
    env_file:
      - path: './superchat-api/.env.production'
        required: true
    depends_on:
      - database

  frontend:
    build: ./superchat-front
    container_name: superchat-front
    restart: always

  nginx:
    image: nginx:latest
    container_name: superchat-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email victorphaelnev@gmail.com -d victoraphael.com.br -d api.superchat.victoraphael.com.br -d superchat.victoraphael.com.br --agree-tos

volumes:
  postgres_data:
  mongodb_data:
