FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm install --frozen-lockfile

FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/package*.json ./

RUN npm ci --only=production --frozen-lockfile && \
    npm cache clean --force

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/next.config.* ./

RUN chown -R nextjs:nodejs /app
USER nextjs

EXPOSE 3000

CMD ["npm", "start"]